# Generated by Django 4.2.2 on 2026-06-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='CRF名称')),
                ('description', models.TextField(blank=True, verbose_name='CRF描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_crfs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'CRF',
                'verbose_name_plural': 'CRF列表',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, verbose_name='患者号')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='是否已提交')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '患者提交记录',
                'verbose_name_plural': '患者提交记录列表',
                'ordering': ['-created_at'],
                'unique_together': {('patient_id', 'submitted_by')},
            },
        ),
        migrations.CreateModel(
            name='CRFSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('data', models.TextField(verbose_name='提交的JSON数据')),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.crf', verbose_name='所属CRF')),
                ('patient_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crf_submissions', to='accounts.patientsubmission', verbose_name='所属患者提交')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': 'CRF提交记录',
                'verbose_name_plural': 'CRF提交记录列表',
                'ordering': ['crf__created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRFField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('field_label', models.CharField(max_length=200, verbose_name='字段标签')),
                ('field_type', models.CharField(choices=[('text', '文本输入'), ('number', '数字输入'), ('date', '日期选择'), ('select', '下拉选择'), ('textarea', '多行文本'), ('radio', '单选按钮'), ('checkbox', '多选框')], max_length=20, verbose_name='字段类型')),
                ('field_order', models.IntegerField(default=0, verbose_name='字段顺序')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('options', models.TextField(blank=True, help_text='用于select/radio/checkbox类型，用逗号分隔各选项', verbose_name='选项（逗号分隔）')),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.crf', verbose_name='所属CRF')),
            ],
            options={
                'verbose_name': 'CRF字段',
                'verbose_name_plural': 'CRF字段列表',
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='CRFDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='草稿JSON数据')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='accounts.crf', verbose_name='所属CRF')),
                ('patient_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crf_drafts', to='accounts.patientsubmission', verbose_name='所属患者提交')),
            ],
            options={
                'verbose_name': 'CRF草稿',
                'verbose_name_plural': 'CRF草稿列表',
                'ordering': ['crf__created_at'],
                'unique_together': {('patient_submission', 'crf')},
            },
        ),
    ]
